version: "3"
services:
  api-database:
    image: mongo
    container_name: "api-database"
    ports:
      - 27017:27017
  api:
    image: satyamchand/cms-demo
    ports:
      - 8080:8080
    links:
      - api-database